### ISSUE TITLE
unsafe for parallel execution

### ISSUE THREAD

**Issue by stuartyeates** [wimmuskee/shell-oaiharvester#2]
Most filesystem access is unsafe for parallel execution (instances of the script running in parallel). Need to:
- uniqify default ${TMP} 
- save xsd somewhere sane
-  uniqify default log file

**Comment by wimmuskee** [comment]
on it

**Comment by wimmuskee** [comment]
just uploaded a change for safe parallel execution, still working on the logfile uniqueness

**Comment by wimmuskee** [comment]
Also made the logfile uniqueness work, it's optional, set logtype to "instance" to make that work. Let me know if those changes work for you.

**Comment by wimmuskee** [comment]
no further comments, i consider this issue closed
