### ISSUE TITLE
earliestDatestamp

### ISSUE THREAD

**Issue by DZielke** [wimmuskee/shell-oaiharvester#3]
Can I get the parameter earliestDatestamp instead from/until?

**Comment by wimmuskee** [comment]
I implemented the use of the Identify earliestDatestamp as the default 'from' value in case of a first harvest. The config from can still be used to override this in case of debugging.

I'm not sure what you're asking with the 'until'.

**Comment by DZielke** [comment]
I understand you correctly that I need nothing to enter for the param 'from' in the config.xml?

For my Harvesting I need the 'earliestDatestamp' respectively the start time from the first dataset.

 

The config.xml for shell-harvester currently looks like this:

...


        <repository id="xxx">
                <baseurl>http://example.de/api/oaipmh</baseurl>
                <metadataprefix>dcndl_simple</metadataprefix>
                <set>testset</set>
       -->    <from>2016-01-01</from>
       -->    <until>2016-11-07</until>
                <conditional>only-context-po.xsl</conditional>
                <recordpath>/tmp/records/repository_id</recordpath>

...

Additional Question for 'until'-param, Is there something like that 'now' e.g.  <until>now</until>?

 

Thanks in advance and cheers

Dennis



Gesendet: Dienstag, 08. November 2016 um 06:25 Uhr
Von: "Wim Muskee" <notifications@github.com>
An: wimmuskee/shell-oaiharvester <shell-oaiharvester@noreply.github.com>
Cc: "Dennis Zielke" <zielke.dennis@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [wimmuskee/shell-oaiharvester] earliestDatestamp (#3)


I implemented the use of the Identify earliestDatestamp as the default 'from' value in case of a first harvest. The config from can still be used to override this in case of debugging.

I'm not sure what you're asking with the 'until'.

**Comment by wimmuskee** [comment]
Ok, for the 0.22 release, you do not need "from" or "until" in your config.xml. By default, the first harvest reads from the Identity earliestTimestamp, and without an "until", it harvests until "now".

Does this answer your questions? (will probably add something in the readme about this as well)

**Comment by DZielke** [comment]
Ok, if I remove the parameters (from, until) in the 0.22 release, then my harvesting-process does not start.

 

That looks so:

----------------------
Starting harvest from: http://iss.ndl.go.jp/api/oaipmh?verb=ListRecords&metadataPrefix=dcndl_simple&set=iss-ndl-opac&from=
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   634  100   634    0     0   1236      0 --:--:-- --:--:-- --:--:--  1235
Error: badArgument - The request includes illegal arguments, is missing required arguments, includes a repeated argument, or values for arguments have an illegal syntax.

----------------------

 

My config.xml

----------------------


<baseurl>http://iss.ndl.go.jp/api/oaipmh</baseurl>
<metadataprefix>dcndl_simple</metadataprefix>
<set>iss-ndl-opac</set>
<conditional>only-context-po.xsl</conditional>
<recordpath>/tmp/records/iss-ndl-opac/repository_id</recordpath>

----------------------

 

Thanks and cheers

Dennis



Gesendet: Dienstag, 08. November 2016 um 16:28 Uhr
Von: "Wim Muskee" <notifications@github.com>
An: wimmuskee/shell-oaiharvester <shell-oaiharvester@noreply.github.com>
Cc: "Dennis Zielke" <zielke.dennis@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [wimmuskee/shell-oaiharvester] earliestDatestamp (#3)


Ok, for the 0.22 release, you do not need "from" or "until" in your config.xml. By default, the first harvest reads from the Identity earliestTimestamp, and without an "until", it harvests until "now".

Does this answer your questions? (will probably add something in the readme about this as well)

**Comment by wimmuskee** [comment]
I see the Identify verb request response is not valid. The 'identify' element should start with a capital. https://www.openarchives.org/OAI/openarchivesprotocol.html#Identify 

That is the reason the earliestDatestamp (and thus the from value) is empty in the request. I will add a valid default in the program later.

**Comment by DZielke** [comment]
Ok, you mean if you change 'identify' in 'Identify' it should runs after it?



Gesendet: Mittwoch, 09. November 2016 um 15:32 Uhr
Von: "Wim Muskee" <notifications@github.com>
An: wimmuskee/shell-oaiharvester <shell-oaiharvester@noreply.github.com>
Cc: "Dennis Zielke" <zielke.dennis@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [wimmuskee/shell-oaiharvester] earliestDatestamp (#3)


I see the Identify verb request response is not valid. The 'identify' element should start with a capital. https://www.openarchives.org/OAI/openarchivesprotocol.html#Identify

That is the reason the earliestDatestamp (and thus the from value) is empty in the request. I will add a valid default in the program later.

**Comment by wimmuskee** [comment]
Yeah, at least, as far as I can see the harvester won't be the problem.

**Comment by wimmuskee** [comment]
Made a small patch preventing to fetch with an empty earliestDatestamp.

However, this won't solve your problem fully, I see the oaiprovider you use is not fully compliant. 
The repository considers "from" a required argument, and only works with datestamps higher than the listed earliestDatestamp. Both behaviours are incorrect use of the [spec](https://www.openarchives.org/OAI/openarchivesprotocol.html#Datestamp).
- "from" is an optional argument, when omitted, the repository gives everything from its listed earliestDatestamp
- "from" value can also be below the listed earliestDatestamp (did not find anything in the spec to suggest otherwise), in my interpretation, the repository also must give everything from the earliestDatestamp

**Comment by wimmuskee** [comment]
ok, no further comments apparently, i consider this issue closed
